# SEO texts: page titles, meta descriptions and category intros in 4 languages.
CAT_SLUG = {
    "hav": "ventilation-systems", "gol": "shading-systems", "kel": "greenhouse-clamps",
    "pro": "profile-clamps", "men": "hinges", "olu": "growing-gutter-accessories", "prf": "gutters-and-profiles",
    "nay": "film-and-clips", "mot": "motors-and-reducers", "fan": "fans",
}
CATS = list(CAT_SLUG)

SEO = {
"en": {
  "home_title": "SERAFIX | Greenhouse Fittings & Ventilation Parts Manufacturer",
  "home_desc": "Manufacturer of greenhouse ventilation, shading, clamp, profile and motor-reducer parts in Türkiye. 103 products, OEM production, export to greenhouse builders.",
  "products_title": "Greenhouse Parts & Accessories Catalogue | SERAFIX",
  "products_desc": "Browse 103 greenhouse parts: rack-and-pinion ventilation, shading systems, pipe clamps, profile clamps, hinges, growing gutter accessories, film clips, motors and fans.",
  "cat_title": "{cat} for Greenhouses | SERAFIX",
  "prod_title": "{name} | {cat} | SERAFIX",
  "prod_suffix": " Made in Türkiye. Request a quote or technical drawing.",
  "oem_title": "OEM & Custom Greenhouse Parts Manufacturing | SERAFIX",
  "oem_desc": "Send your drawing or sample: we manufacture custom greenhouse clamps, brackets and steel parts with your branding and packaging. OEM production in Türkiye.",
  "quality_title": "Quality Control, Production & Export | SERAFIX",
  "quality_desc": "How SERAFIX produces and tests greenhouse parts: raw material checks, galvanized coating, dimensional control and export packaging for worldwide delivery.",
  "downloads_title": "Downloads: Catalogue PDF, Drawings & CAD | SERAFIX",
  "downloads_desc": "Download the SERAFIX greenhouse parts catalogue in PDF, technical drawings and CAD files for ventilation, shading, clamp and motor products.",
  "org_desc": "Manufacturer of greenhouse ventilation, shading and structure fittings.",
  "cat_intro": {
    "hav": "Rack-and-pinion ventilation parts for roof and side vents: racks, pinions, ball-bearing hangers, shafts and couplings for galvanized pipe systems.",
    "gol": "Shading and thermal screen components: wire guides, pulleys, push-pull profiles, screen clips and drive parts for greenhouse curtain systems.",
    "kel": "Galvanized steel pipe clamps for greenhouse structures: cross clamps, T-clamps, parallel clamps and arch connectors for every pipe diameter.",
    "pro": "Profile clamps and connectors that fix aluminium and steel profiles to pipes, trusses and columns in multi-span greenhouses.",
    "men": "Hinges for greenhouse vents and doors, built for continuous movement, outdoor exposure and long service life.",
    "olu": "Plastic drains and drain covers for growing gutters used in soilless (substrate and hydroponic) cultivation, in large and small sizes for controlled drainage.",
    "prf": "Rain gutters and special profiles for greenhouse structures: gutter profiles, lock and channel profiles and other custom roll-formed sections.",
    "nay": "Film fixing systems: lock profiles, wiggle wires, film clips and clips for polyethylene film and nets.",
    "mot": "Motor reducers and drive units for ventilation and shading systems, with limit switches and mounting accessories.",
    "fan": "Greenhouse circulation and exhaust fans for air movement, cooling and humidity control."},
},
"tr": {
  "home_title": "SERAFIX | Sera Bağlantı Elemanları ve Havalandırma Parçaları",
  "home_desc": "Türkiye'de sera havalandırma, gölgeleme, kelepçe, profil ve motor redüktör parçaları üreticisi. 103 ürün, OEM üretim, sera kurucularına ihracat.",
  "products_title": "Sera Malzemeleri ve Aksesuarları Kataloğu | SERAFIX",
  "products_desc": "103 sera parçasını inceleyin: kremayer havalandırma, gölgeleme sistemleri, boru kelepçeleri, profil kelepçeleri, menteşeler, gutter aksesuarları, naylon klipsleri, motor ve fanlar.",
  "cat_title": "Sera {cat} | SERAFIX",
  "prod_title": "{name} | {cat} | SERAFIX",
  "prod_suffix": " Türkiye'de üretilmiştir. Fiyat teklifi veya teknik çizim isteyin.",
  "oem_title": "OEM ve Özel Sera Parçası Üretimi | SERAFIX",
  "oem_desc": "Çiziminizi veya numunenizi gönderin: Sera kelepçesi, bağlantı ve çelik parçaları kendi markanız ve ambalajınızla üretiyoruz. Türkiye'de OEM üretim.",
  "quality_title": "Kalite Kontrol, Üretim ve İhracat | SERAFIX",
  "quality_desc": "SERAFIX sera parçalarını nasıl üretir ve test eder: hammadde kontrolü, galvaniz kaplama, ölçü kontrolü ve dünya geneline ihracat ambalajı.",
  "downloads_title": "İndirmeler: PDF Katalog, Çizimler ve CAD | SERAFIX",
  "downloads_desc": "SERAFIX sera parçaları kataloğunu PDF olarak, havalandırma, gölgeleme, kelepçe ve motor ürünlerinin teknik çizim ve CAD dosyalarını indirin.",
  "org_desc": "Sera havalandırma, gölgeleme ve konstrüksiyon bağlantı elemanları üreticisi.",
  "cat_intro": {
    "hav": "Çatı ve yan pencereler için kremayer-pinyon havalandırma parçaları: kremayer, pinyon, rulmanlı askı, mil ve kaplinler.",
    "gol": "Gölgeleme ve termal perde parçaları: tel kılavuzları, makaralar, itme-çekme profilleri, perde klipsleri ve tahrik parçaları.",
    "kel": "Sera konstrüksiyonu için galvanizli çelik boru kelepçeleri: çapraz, T, paralel kelepçeler ve kemer bağlantıları, her boru çapı için.",
    "pro": "Çok bölmeli seralarda alüminyum ve çelik profilleri boru, makas ve dikmelere sabitleyen profil kelepçeleri ve bağlantıları.",
    "men": "Sürekli hareket ve dış ortam koşullarına dayanıklı, uzun ömürlü sera penceresi ve kapı menteşeleri.",
    "olu": "Topraksız tarımda (substrat ve hidroponik) kullanılan yetiştirme gutter'ları için plastik gider ve gider kapakları. Kontrollü drenaj için büyük ve küçük boy seçenekleri.",
    "prf": "Sera konstrüksiyonu için yağmur olukları ve özel profiller: oluk profilleri, kilit ve kanal profilleri ile diğer özel rulo form profiller.",
    "nay": "Naylon sabitleme sistemleri: kilit profilleri, zigzag teller ve polietilen örtü ile file için klipsler.",
    "mot": "Havalandırma ve gölgeleme sistemleri için motor redüktörler ve tahrik üniteleri, limit şalteri ve montaj aksesuarlarıyla.",
    "fan": "Hava sirkülasyonu, serinletme ve nem kontrolü için sera sirkülasyon ve egzoz fanları."},
},
"ru": {
  "home_title": "SERAFIX | Комплектующие для теплиц: хомуты и вентиляция",
  "home_desc": "Производитель комплектующих для теплиц в Турции: вентиляция, зашторивание, хомуты, профили, мотор-редукторы. 103 изделия, OEM-производство, экспорт.",
  "products_title": "Каталог комплектующих для теплиц | SERAFIX",
  "products_desc": "103 изделия для теплиц: реечная вентиляция, системы зашторивания, трубные хомуты, профильные зажимы, петли, комплектующие лотков выращивания, крепление плёнки, мотор-редукторы и вентиляторы.",
  "cat_title": "{cat} для теплиц | SERAFIX",
  "prod_title": "{name} | {cat} | SERAFIX",
  "prod_suffix": " Произведено в Турции. Запросите цену или чертёж.",
  "oem_title": "OEM и производство комплектующих для теплиц по чертежам | SERAFIX",
  "oem_desc": "Пришлите чертёж или образец: изготовим хомуты, кронштейны и стальные детали для теплиц под вашим брендом и в вашей упаковке. OEM-производство в Турции.",
  "quality_title": "Контроль качества, производство и экспорт | SERAFIX",
  "quality_desc": "Как SERAFIX производит и проверяет комплектующие для теплиц: входной контроль металла, оцинковка, контроль размеров и экспортная упаковка.",
  "downloads_title": "Загрузки: каталог PDF, чертежи и CAD | SERAFIX",
  "downloads_desc": "Скачайте каталог комплектующих для теплиц SERAFIX в PDF, технические чертежи и CAD-файлы.",
  "org_desc": "Производитель комплектующих для вентиляции, зашторивания и каркаса теплиц.",
  "cat_intro": {
    "hav": "Комплектующие реечной вентиляции для кровельных и боковых форточек: рейки, шестерни, подшипниковые подвесы, валы и муфты.",
    "gol": "Комплектующие систем зашторивания и энергосберегающих экранов: направляющие, ролики, профили, клипсы и детали привода.",
    "kel": "Оцинкованные стальные хомуты для каркаса теплиц: крестовые, Т-образные, параллельные хомуты и соединители арок для всех диаметров труб.",
    "pro": "Профильные зажимы и соединители для крепления алюминиевых и стальных профилей к трубам, фермам и колоннам блочных теплиц.",
    "men": "Петли для форточек и дверей теплиц, рассчитанные на постоянное движение и работу на открытом воздухе.",
    "olu": "Пластиковые сливы и заглушки-сливы для лотков выращивания в беспочвенной культуре (субстрат и гидропоника), большого и малого размера для контролируемого дренажа.",
    "prf": "Водосточные желоба и специальные профили для каркаса теплиц: профили желобов, замковые и канальные профили и другие профили по заказу.",
    "nay": "Системы крепления плёнки: замковые профили, зигзагообразная проволока и клипсы для полиэтиленовой плёнки и сеток.",
    "mot": "Мотор-редукторы и приводы для систем вентиляции и зашторивания с концевыми выключателями и крепёжом.",
    "fan": "Циркуляционные и вытяжные вентиляторы для теплиц: движение воздуха, охлаждение и контроль влажности."},
},
"ar": {
  "home_title": "SERAFIX | مصنّع ملحقات البيوت المحمية: مشابك، تهوية وتظليل",
  "home_desc": "مصنّع في تركيا لقطع تهوية وتظليل البيوت المحمية والمشابك والبروفيلات ومخفضات المحركات. 103 منتجات، تصنيع OEM وتصدير لشركات إنشاء البيوت المحمية.",
  "products_title": "كتالوج قطع وملحقات البيوت المحمية | SERAFIX",
  "products_desc": "تصفّح 103 قطع للبيوت المحمية: تهوية بالجريدة المسننة، أنظمة التظليل، مشابك الأنابيب، مشابك البروفيل، المفصلات، ملحقات قنوات الزراعة، مثبتات النايلون، المحركات والمراوح.",
  "cat_title": "{cat} للبيوت المحمية | SERAFIX",
  "prod_title": "{name} | {cat} | SERAFIX",
  "prod_suffix": " صُنع في تركيا. اطلب عرض سعر أو رسماً فنياً.",
  "oem_title": "تصنيع OEM وقطع مخصصة للبيوت المحمية | SERAFIX",
  "oem_desc": "أرسل رسمك الفني أو العينة: نصنّع مشابك وحوامل وقطعاً فولاذية للبيوت المحمية بعلامتك التجارية وتغليفك. تصنيع OEM في تركيا.",
  "quality_title": "مراقبة الجودة والإنتاج والتصدير | SERAFIX",
  "quality_desc": "كيف تنتج SERAFIX قطع البيوت المحمية وتختبرها: فحص المواد الخام، الطلاء المجلفن، فحص الأبعاد وتغليف التصدير.",
  "downloads_title": "التنزيلات: كتالوج PDF والرسومات وملفات CAD | SERAFIX",
  "downloads_desc": "نزّل كتالوج قطع البيوت المحمية من SERAFIX بصيغة PDF والرسومات الفنية وملفات CAD.",
  "org_desc": "مصنّع قطع التهوية والتظليل والهيكل للبيوت المحمية.",
  "cat_intro": {
    "hav": "قطع التهوية بالجريدة المسننة لفتحات السقف والجوانب: جرائد مسننة، تروس، معلّقات بمحامل، أعمدة ووصلات.",
    "gol": "مكونات أنظمة التظليل والستائر الحرارية: موجهات الأسلاك، بكرات، بروفيلات، مشابك الستائر وقطع الإدارة.",
    "kel": "مشابك أنابيب فولاذية مجلفنة لهياكل البيوت المحمية: مشابك متقاطعة وعلى شكل T ومتوازية ووصلات أقواس لكل أقطار الأنابيب.",
    "pro": "مشابك ووصلات بروفيل لتثبيت البروفيلات الألمنيوم والفولاذ على الأنابيب والجمالونات والأعمدة.",
    "men": "مفصلات لفتحات وأبواب البيوت المحمية مصممة للحركة المستمرة والعمل في الهواء الطلق.",
    "olu": "مصارف وأغطية تصريف بلاستيكية لقنوات الزراعة المستخدمة في الزراعة بدون تربة (الركائز والزراعة المائية)، بمقاسات كبيرة وصغيرة لتصريف منضبط.",
    "prf": "مزاريب مياه الأمطار وبروفيلات خاصة لهياكل البيوت المحمية: بروفيلات المزاريب وبروفيلات القفل والقنوات وغيرها من البروفيلات المشكّلة حسب الطلب.",
    "nay": "أنظمة تثبيت النايلون: بروفيلات قفل، أسلاك متعرجة ومشابك لأغطية البولي إيثيلين والشباك.",
    "mot": "مخفضات محركات ووحدات إدارة لأنظمة التهوية والتظليل مع مفاتيح نهاية الشوط وملحقات التركيب.",
    "fan": "مراوح تدوير وشفط للبيوت المحمية لتحريك الهواء والتبريد والتحكم في الرطوبة."},
},
}
